name : Demo workflow
on: 
  pull_request
  
jobs:
  Markdown-Linter
    runs-on: windows
    steps:
      -name: Check code
      uses: actions/checkout@v2
      - name: Markodown Linting Action
      uses : avto-dev/markdown-lint@v1.5.0
      with:
        args: '.'
        config: '.markdownlint.yml'
