name: Pull Request Workflow
on: 
  pull_request

jobs: 
  Markdown-Linter:
    runs-on: windows
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: markdownlint-cli
      uses: avto-dev/markdown-lint@v1
      with:
        args: '.'
        config: 'markdownlint.yml'
